x <- nasa
x$DECISION_DENSITY=x$CONDITION_COUNT/x$DECISION_COUNT
x$IS_NAN_DECISION_DENSITY <- is.nan(x$DECISION_DENSITY)
x$DECISION_DENSITY[is.nan(x$DECISION_DENSITY)] <- 0

x$CYCLOMATIC_DENSITY <- x$CYCLOMATIC_COMPLEXITY/x$LOC_TOTAL
x$IS_INF_CYCLOMATIC_DENSITY <- as.numeric(is.infinite(x$CYCLOMATIC_DENSITY))
x$CYCLOMATIC_DENSITY[is.infinite(x$CYCLOMATIC_DENSITY)] <- 100

x$DESIGN_DENSITY=x$DESIGN_COMPLEXITY/x$CYCLOMATIC_COMPLEXITY

x$ESSENTIAL_DENSITY=(x$ESSENTIAL_COMPLEXITY-1)/(x$CYCLOMATIC_COMPLEXITY-1)
x$IS_NAN_ESSENTIAL_DENSITY <- is.nan(x$ESSENTIAL_DENSITY)
x$ESSENTIAL_DENSITY[is.nan(x$ESSENTIAL_DENSITY)] <- 0

x$MAINTENANCE_SEVERITY=x$ESSENTIAL_COMPLEXITY/x$CYCLOMATIC_COMPLEXITY

x$NORMALIZED_CYLOMATIC_COMPLEXITY=x$CYCLOMATIC_COMPLEXITY/x$NUMBER_OF_LINES
isna <- is.na(x$NUMBER_OF_LINES)
  x$NORMALIZED_CYLOMATIC_COMPLEXITY[isna] <- x$CYCLOMATIC_COMPLEXITY[isna]/(x$LOC_CODE_AND_COMMENT[isna]+x$LOC_COMMENTS[isna]+x$LOC_EXECUTABLE[isna]+x$LOC_BLANK[isna])
x$IS_INF_NORMALIZED_CYLOMATIC_COMPLEXITY <- is.infinite(x$NORMALIZED_CYLOMATIC_COMPLEXITY)
x$NORMALIZED_CYLOMATIC_COMPLEXITY[is.infinite(x$NORMALIZED_CYLOMATIC_COMPLEXITY)] <- 100

x$PERCENT_COMMENTS=(x$LOC_COMMENTS+x$LOC_CODE_AND_COMMENT)/(x$LOC_CODE_AND_COMMENT+x$LOC_COMMENTS+x$LOC_EXECUTABLE)
x$IS_NAN_PERCENT_COMMENTS <- is.nan(x$PERCENT_COMMENTS)
x$PERCENT_COMMENTS[is.nan(x$PERCENT_COMMENTS)] <- 0

isna <- is.na(x$NUMBER_OF_LINES)
x$NUMBER_OF_LINES[isna] <- x$LOC_CODE_AND_COMMENT[isna]+x$LOC_COMMENTS[isna]+x$LOC_EXECUTABLE[isna]+x$LOC_BLANK[isna]

isna <- is.na(x$LOC_BLANK)
x$LOC_BLANK[isna] <- x$LOC_CODE_AND_COMMENT[isna]+x$LOC_COMMENTS[isna]+x$LOC_EXECUTABLE[isna] - x$NUMBER_OF_LINES[isna]
x$LOC_BLANK[x$LOC_BLANK<0] <- 0
